---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - manifests/externalsecret.yaml
  - manifests/renovatejob.yaml
  - manifests/httproute.yaml
components:
  - ../../components/namespace
helmCharts:
  - name: renovate-operator
    repo: oci://ghcr.io/mogenius/helm-charts
    version: 3.8.3
    releaseName: renovate-operator
    namespace: renovate
    valuesFile: manifests/values.yaml
