---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app adguard
  namespace: *app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: *app
      initContainers:
        - name: adguard-init
          image: busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "cp /home/AdGuardHome.yaml /config/AdGuardHome.yaml; chmod 644
                /config/AdGuardHome.yaml",
            ]
          volumeMounts:
            - mountPath: /home
              name: adguard-secret
            - mountPath: /config
              name: adguard-conf
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dnstcp
              protocol: TCP
            - containerPort: 3000
              name: http-initial
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-conf
              mountPath: /opt/adguardhome/conf
          resources:
            requests:
              memory: 300Mi
              cpu: "15m"
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe: &probe
            exec:
              command:
                - /bin/sh
                - -c
                - nslookup localhost 127.0.0.1
          readinessProbe: *probe
        - name: adguard-exporter
          image: ghcr.io/sholdee/adguard-exporter:2.1.1@sha256:9d7565dd3db81899b499972c5f4e56dead5f28f9f71213b4e96a65d48d3ffcd7
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work
          resources:
            requests:
              memory: 100Mi
              cpu: "5m"
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
      volumes:
        - emptyDir: {}
          name: adguard-data
        - emptyDir: {}
          name: adguard-conf
        - name: adguard-secret
          secret:
            secretName: adguard-secret
