{
 "title": "Gravity",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Gravity Cluster",
    "query": {
     "query": "label_values(gravity_instance_roles, instance)"
    }
   },
   {
    "name": "dns_zone",
    "label": "DNS Zone",
    "query": {
     "query": "label_values(gravity_dns_queries, zone)"
    }
   },
   {
    "name": "dhcp_scope",
    "label": "DHCP Scope",
    "query": {
     "query": "label_values(gravity_dhcp_requests, scope)"
    }
   },
   {
    "name": "log_stream",
    "label": "Log stream",
    "query": "{syslog_identifier=\"gravity\"}"
   }
  ]
 },
 "panels": [
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\", instance=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\", instance=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Client/Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Client Traffic In"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$cluster\"}[$__rate_interval]) * -1",
     "legendFormat": "{{instance}} Client Traffic Out"
    },
    {
     "expr": "rate(etcd_network_peer_received_bytes_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Peer Traffic In"
    },
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total{instance=~\"$cluster\"}[$__rate_interval]) * -1",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(etcd_network_active_peers{instance=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$cluster\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "DNS Queries/second (per Zone)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (zone) (rate(gravity_dns_queries{instance=~\"$cluster\", zone=~\"$dns_zone\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries/second (per Handler)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(gravity_dns_queries{instance=~\"$cluster\", zone=~\"$dns_zone\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries/second (by instance)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(gravity_dns_queries{instance=~\"$cluster\", zone=~\"$dns_zone\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Clients",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(5, sum(rate($log_stream |= `` | json | msg=\"DNS Query\"[5m])) by (client))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "DNS Query names",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "topk(5, sum(rate($log_stream |= `` | json qn=\"queryNames[0]\",msg=\"msg\" | __error__ != \"JSONParserErr\" | msg=\"DNS Query\"[5m])) by (qn))",
     "legendFormat": "{{qn}}"
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DHCP Requests/second (per Type)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (type) (rate(gravity_dhcp_requests{instance=~\"$cluster\", scope=~\"$dhcp_scope\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP Requests/second (per Instance)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(gravity_dhcp_requests{instance=~\"$cluster\", scope=~\"$dhcp_scope\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}