#!/usr/bin/env bash
# shellcheck shell=bash

NODE_API_WAIT_TIMEOUT="${NODE_API_WAIT_TIMEOUT:-180}"
NODE_LONGHORN_WAIT_TIMEOUT="${NODE_LONGHORN_WAIT_TIMEOUT:-300}"

NODE_K3S_CONFIG_DIR="${NODE_K3S_CONFIG_DIR:-$BOOTSTRAP_K3S_CONFIG_DIR}"
NODE_K3S_SERVER_DIR="${NODE_K3S_SERVER_DIR:-$BOOTSTRAP_K3S_SERVER_DIR}"
NODE_K3S_KUBECONFIG="${NODE_K3S_KUBECONFIG:-${NODE_K3S_CONFIG_DIR}/k3s.yaml}"
NODE_K3S_ETCD_TLS_DIR="${NODE_K3S_ETCD_TLS_DIR:-${NODE_K3S_SERVER_DIR}/tls/etcd}"
NODE_K3S_ETCD_DATA_DIR="${NODE_K3S_ETCD_DATA_DIR:-${NODE_K3S_SERVER_DIR}/db/etcd}"
NODE_K3S_SQLITE_DB="${NODE_K3S_SQLITE_DB:-${NODE_K3S_SERVER_DIR}/db/state.db}"
NODE_K3S_KUBE_PROXY_DISABLE_CONFIG="${NODE_K3S_KUBE_PROXY_DISABLE_CONFIG:-${NODE_K3S_CONFIG_DIR}/config.yaml.d/90-home-ops-kube-proxy.yaml}"

NODE_REIMAGE_DEFAULT_DISK="${NODE_REIMAGE_DEFAULT_DISK:-/dev/nvme0n1}"
NODE_REIMAGE_DEFAULT_STAGE_DIR="${NODE_REIMAGE_DEFAULT_STAGE_DIR:-/boot/firmware/home-ops-reimage}"
NODE_REIMAGE_BOOT_CONFIG="${NODE_REIMAGE_BOOT_CONFIG:-/boot/firmware/tryboot.txt}"
NODE_REIMAGE_IMAGE_DEFAULT_BASE_LAYER="${NODE_REIMAGE_IMAGE_DEFAULT_BASE_LAYER:-trixie-minbase}"
NODE_REIMAGE_IMAGE_DEFAULT_INTERFACE="${NODE_REIMAGE_IMAGE_DEFAULT_INTERFACE:-eth0}"
NODE_REIMAGE_IMAGE_DEFAULT_PREFIX="${NODE_REIMAGE_IMAGE_DEFAULT_PREFIX:-24}"

NODE_REIMAGE_ANSIBLE_DEFAULTS_FILE="${NODE_REIMAGE_ANSIBLE_DEFAULTS_FILE:-${BOOTSTRAP_DIR}/ansible/home-ops/vars/defaults.yml}"

NODE_KERNEL_DIR="${NODE_KERNEL_DIR:-${NODE_SCRIPT_DIR}/kernel}"
NODE_KERNEL_SOURCE_LOCK="${NODE_KERNEL_SOURCE_LOCK:-${NODE_KERNEL_DIR}/source.yaml}"
NODE_KERNEL_CONFIG_DELTA="${NODE_KERNEL_CONFIG_DELTA:-${NODE_KERNEL_DIR}/config.2712.delta}"
NODE_KERNEL_BUILD_GUEST_SCRIPT="${NODE_KERNEL_BUILD_GUEST_SCRIPT:-${NODE_KERNEL_DIR}/build-guest.sh}"
NODE_KERNEL_VERIFY_SCRIPT="${NODE_KERNEL_VERIFY_SCRIPT:-${NODE_KERNEL_DIR}/verify-kernel-build.sh}"
NODE_KERNEL_OUTPUT_ROOT="${NODE_KERNEL_OUTPUT_ROOT:-${BOOTSTRAP_DIR}/.out/kernel}"
NODE_KERNEL_ARCHIVE_URL="${NODE_KERNEL_ARCHIVE_URL:-http://archive.raspberrypi.com/debian}"
NODE_KERNEL_ARCHIVE_SUITE="${NODE_KERNEL_ARCHIVE_SUITE:-trixie}"
NODE_KERNEL_ARCHIVE_COMPONENT="${NODE_KERNEL_ARCHIVE_COMPONENT:-main}"
NODE_KERNEL_ABI_SUFFIX="${NODE_KERNEL_ABI_SUFFIX:-+rpt}"
# shellcheck disable=SC2034
NODE_KERNEL_FLAVOUR="rpi-2712"
# shellcheck disable=SC2034
NODE_KERNEL_BUILD_SCHEMA="home-ops.node-kernel-build/v1"
# shellcheck disable=SC2034
NODE_KERNEL_BUILD_LABEL_KEY="node.home-ops.sh/kernel-build"
# shellcheck disable=SC2034
NODE_KERNEL_VERIFY_BIN="/usr/local/sbin/home-ops-verify-kernel-build"
NODE_CURL_BIN="${NODE_CURL_BIN:-curl}"
NODE_GPGV_BIN="${NODE_GPGV_BIN:-gpgv}"
