#!/usr/bin/env bash
# shellcheck shell=bash

NODE_API_WAIT_TIMEOUT="${NODE_API_WAIT_TIMEOUT:-180}"
NODE_LONGHORN_WAIT_TIMEOUT="${NODE_LONGHORN_WAIT_TIMEOUT:-300}"

NODE_K3S_CONFIG_DIR="${NODE_K3S_CONFIG_DIR:-$BOOTSTRAP_K3S_CONFIG_DIR}"
NODE_K3S_SERVER_DIR="${NODE_K3S_SERVER_DIR:-$BOOTSTRAP_K3S_SERVER_DIR}"
NODE_K3S_KUBECONFIG="${NODE_K3S_KUBECONFIG:-${NODE_K3S_CONFIG_DIR}/k3s.yaml}"
NODE_K3S_ETCD_TLS_DIR="${NODE_K3S_ETCD_TLS_DIR:-${NODE_K3S_SERVER_DIR}/tls/etcd}"
NODE_K3S_ETCD_DATA_DIR="${NODE_K3S_ETCD_DATA_DIR:-${NODE_K3S_SERVER_DIR}/db/etcd}"
NODE_K3S_SQLITE_DB="${NODE_K3S_SQLITE_DB:-${NODE_K3S_SERVER_DIR}/db/state.db}"
NODE_K3S_KUBE_PROXY_DISABLE_CONFIG="${NODE_K3S_KUBE_PROXY_DISABLE_CONFIG:-${NODE_K3S_CONFIG_DIR}/config.yaml.d/90-home-ops-kube-proxy.yaml}"

NODE_REIMAGE_DEFAULT_DISK="${NODE_REIMAGE_DEFAULT_DISK:-/dev/nvme0n1}"
NODE_REIMAGE_DEFAULT_STAGE_DIR="${NODE_REIMAGE_DEFAULT_STAGE_DIR:-/boot/firmware/home-ops-reimage}"
NODE_REIMAGE_BOOT_CONFIG="${NODE_REIMAGE_BOOT_CONFIG:-/boot/firmware/tryboot.txt}"
NODE_REIMAGE_IMAGE_DEFAULT_BASE_LAYER="${NODE_REIMAGE_IMAGE_DEFAULT_BASE_LAYER:-trixie-minbase}"
NODE_REIMAGE_IMAGE_DEFAULT_INTERFACE="${NODE_REIMAGE_IMAGE_DEFAULT_INTERFACE:-eth0}"
NODE_REIMAGE_IMAGE_DEFAULT_PREFIX="${NODE_REIMAGE_IMAGE_DEFAULT_PREFIX:-24}"
