#!/usr/bin/env bash
# shellcheck shell=bash

# Kernel source lock and build helpers for the home-ops BTF kernel. The lock
# (kernel/source.yaml) pins the Raspberry Pi OS kernel source package; builds
# live under NODE_KERNEL_OUTPUT_ROOT/<build-id>.

node_kernel_fetch() {
  local url="$1"
  local dest="$2"
  "$NODE_CURL_BIN" -fsSL --retry 3 --connect-timeout 30 -o "$dest" "$url" || node_die "download failed: ${url}"
}

# node_kernel_release_sha256_entry RELEASE PATH prints "<sha256> <size>" for PATH
# from the SHA256 section of a verified Release file.
node_kernel_release_sha256_entry() {
  local release="$1"
  local path="$2"
  awk -v path="$path" '
    /^[^ ]/ {in_sha256 = ($0 == "SHA256:")}
    in_sha256 && NF == 3 && $3 == path {print $1, $2; found = 1; exit}
    END {exit found ? 0 : 1}
  ' "$release"
}

# node_kernel_source_stanzas SOURCES PACKAGE prints every Sources paragraph whose
# Package field is exactly PACKAGE.
node_kernel_source_stanzas() {
  local sources="$1"
  local package="$2"
  awk -v package="$package" '
    BEGIN {RS = ""; FS = "\n"}
    {
      for (i = 1; i <= NF; i++) {
        if ($i == "Package: " package) {
          printf "%s\n\n", $0
          next
        }
      }
    }
  ' "$sources"
}

# node_kernel_stanza_checksums prints "<name> <sha256> <size>" per
# Checksums-Sha256 entry of the stanza on stdin.
node_kernel_stanza_checksums() {
  awk '
    /^[^ ]/ {in_block = ($0 ~ /^Checksums-Sha256:[[:space:]]*$/); next}
    in_block && NF == 3 {print $3, $1, $2}
  '
}

node_kernel_release_for_version() {
  local upstream="${1#*:}"
  printf '%s%s-%s\n' "${upstream%%-*}" "$NODE_KERNEL_ABI_SUFFIX" "$NODE_KERNEL_FLAVOUR"
}

node_kernel_write_source_lock() {
  local output="$1"
  local version="$2"
  local suffix="$3"
  local release="$4"
  local archive_url="$5"
  local directory="$6"
  local files="$7"
  local delta_sha="$8"
  local files_json

  files_json="$(
    awk 'NF == 3 {printf "%s\t%s\t%s\n", $1, $2, $3}' <<<"$files" |
      "$NODE_JQ_BIN" -R -s -c 'split("\n") | map(select(length > 0) | split("\t") | {name: .[0], size: (.[2] | tonumber), sha256: .[1]})'
  )" || node_die "could not encode kernel source files"
  mkdir -p "$(dirname "$output")"
  if ! {
    printf '%s\n' '---' \
      '# Generated by just node-kernel-source-lock. Pins the Raspberry Pi OS kernel' \
      '# source package that just node-kernel-build rebuilds with config.2712.delta.' \
      '# Hashes come from the archive Sources index after verifying the InRelease' \
      '# signature. Do not edit by hand: after changing config.2712.delta, rerun' \
      '# just node-kernel-source-lock --build-suffix with a new suffix.'
    # shellcheck disable=SC2016
    "$NODE_JQ_BIN" -n \
      --arg version "$version" \
      --arg suffix "$suffix" \
      --arg configDeltaSha256 "$delta_sha" \
      --arg release "$release" \
      --arg archive "$archive_url" \
      --arg suite "$NODE_KERNEL_ARCHIVE_SUITE" \
      --arg component "$NODE_KERNEL_ARCHIVE_COMPONENT" \
      --arg directory "$directory" \
      --argjson files "$files_json" \
      '{
        package: "linux",
        version: $version,
        buildSuffix: $suffix,
        configDeltaSha256: $configDeltaSha256,
        kernelRelease: $release,
        archiveUrl: $archive,
        suite: $suite,
        component: $component,
        directory: $directory,
        files: $files
      }' |
      "$NODE_YQ_BIN" -P
  } >"${output}.tmp"; then
    rm -f "${output}.tmp"
    node_die "could not render kernel source lock ${output}"
  fi
  mv "${output}.tmp" "$output"
}

node_kernel_lock_source() {
  local keyring="$1"
  local work_dir="$2"
  local output="$3"
  local requested_suffix="$4"
  local base="${NODE_KERNEL_ARCHIVE_URL%/}"
  local suite="$NODE_KERNEL_ARCHIVE_SUITE"
  local sources_path="${NODE_KERNEL_ARCHIVE_COMPONENT}/source/Sources.gz"
  local entry expected_sha expected_size stanzas stanza_count version directory files suffix release
  local name sha size dsc_count=0 delta_sha locked_version="" locked_suffix="" locked_delta_sha=""
  local version_re='^[0-9]+:[0-9][A-Za-z0-9.+~-]*$'
  local directory_re='^pool/[A-Za-z0-9/._+-]+$'
  local name_re='^[A-Za-z0-9][A-Za-z0-9.+~_-]*$'
  local sha_re='^[0-9a-f]{64}$'
  local size_re='^[0-9]+$'
  local suffix_re='^\+btf[1-9][0-9]*$'

  keyring="$(cd "$(dirname "$keyring")" && pwd)/$(basename "$keyring")"
  node_log "verifying ${base}/dists/${suite}/InRelease"
  node_kernel_fetch "${base}/dists/${suite}/InRelease" "${work_dir}/InRelease"
  if ! "$NODE_GPGV_BIN" --keyring "$keyring" --output - "${work_dir}/InRelease" >"${work_dir}/Release" 2>"${work_dir}/gpgv.log"; then
    cat "${work_dir}/gpgv.log" >&2
    node_die "InRelease signature verification failed for ${base}/dists/${suite}"
  fi
  awk -v suite="$suite" '/^[^ ]/ && ($0 == "Codename: " suite || $0 == "Suite: " suite) {found = 1} END {exit found ? 0 : 1}' "${work_dir}/Release" ||
    node_die "signed InRelease is not for suite ${suite}"

  entry="$(node_kernel_release_sha256_entry "${work_dir}/Release" "$sources_path")" ||
    node_die "signed InRelease does not list ${sources_path}"
  read -r expected_sha expected_size <<<"$entry"
  node_kernel_fetch "${base}/dists/${suite}/${sources_path}" "${work_dir}/Sources.gz"
  if [[ "$(node_reimage_sha256_file "${work_dir}/Sources.gz")" != "$expected_sha" ||
    "$(wc -c <"${work_dir}/Sources.gz" | tr -d ' ')" != "$expected_size" ]]; then
    node_die "${sources_path} does not match the signed InRelease (retry if the archive was just updated)"
  fi
  gzip -dc "${work_dir}/Sources.gz" >"${work_dir}/Sources" || node_die "could not decompress ${sources_path}"

  stanzas="$(node_kernel_source_stanzas "${work_dir}/Sources" linux)"
  stanza_count="$(grep -c '^Package: linux$' <<<"$stanzas" || true)"
  [[ "$stanza_count" == 1 ]] ||
    node_die "expected exactly one linux source package in ${sources_path}, found ${stanza_count}"

  version="$(sed -n 's/^Version: //p' <<<"$stanzas")"
  directory="$(sed -n 's/^Directory: //p' <<<"$stanzas")"
  files="$(node_kernel_stanza_checksums <<<"$stanzas")"
  [[ "$version" =~ $version_re ]] || node_die "unexpected linux source version: ${version}"
  [[ "$directory" =~ $directory_re && "$directory" != *..* ]] || node_die "unexpected linux source directory: ${directory}"
  [[ -n "$files" ]] || node_die "linux source package lists no Checksums-Sha256 files"
  while read -r name sha size; do
    [[ "$name" =~ $name_re ]] || node_die "unsafe linux source file name: ${name}"
    [[ "$sha" =~ $sha_re ]] || node_die "invalid sha256 for ${name}"
    [[ "$size" =~ $size_re ]] || node_die "invalid size for ${name}"
    if [[ "$name" == *.dsc ]]; then
      dsc_count=$((dsc_count + 1))
    fi
  done <<<"$files"
  [[ "$dsc_count" == 1 ]] || node_die "linux source package must list exactly one .dsc, found ${dsc_count}"

  [[ -f "$NODE_KERNEL_CONFIG_DELTA" ]] || node_die "kernel config delta not found: ${NODE_KERNEL_CONFIG_DELTA}"
  delta_sha="$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")"
  if [[ -f "$output" ]]; then
    locked_version="$("$NODE_YQ_BIN" -r '.version // ""' "$output")"
    locked_suffix="$("$NODE_YQ_BIN" -r '.buildSuffix // ""' "$output")"
    locked_delta_sha="$("$NODE_YQ_BIN" -r '.configDeltaSha256 // ""' "$output")"
  fi
  if [[ -n "$requested_suffix" ]]; then
    suffix="$requested_suffix"
  elif [[ "$locked_version" == "$version" ]]; then
    suffix="$locked_suffix"
  else
    suffix="+btf1"
  fi
  [[ "$suffix" =~ $suffix_re ]] || node_die "invalid kernel build suffix: ${suffix}"
  # A build suffix names one kernel build per source version: moving to another
  # suffix must move forward, or two different builds share a package version.
  if [[ "$locked_version" == "$version" && "$locked_suffix" != "$suffix" ]]; then
    [[ "$locked_suffix" =~ $suffix_re ]] || node_die "invalid buildSuffix in ${output}: ${locked_suffix}"
    ((${suffix#+btf} > ${locked_suffix#+btf})) ||
      node_die "build suffix ${suffix} must be greater than ${locked_suffix} for ${version}"
  fi
  if [[ "$locked_version" == "$version" && "$locked_suffix" == "$suffix" && "$locked_delta_sha" != "$delta_sha" ]]; then
    node_die "config.2712.delta changed since ${output} pinned ${version}${suffix}; rerun with --build-suffix and a new suffix"
  fi

  release="$(node_kernel_release_for_version "$version")"
  node_kernel_write_source_lock "$output" "$version" "$suffix" "$release" "$base" "$directory" "$files" "$delta_sha"
  printf 'kernel_source_version=%s\n' "$version"
  printf 'kernel_build_suffix=%s\n' "$suffix"
  printf 'kernel_release=%s\n' "$release"
  printf 'source_lock=%s\n' "$output"
}

node_kernel_lock_field() {
  "$NODE_YQ_BIN" -r ".${1} // \"\"" "$NODE_KERNEL_SOURCE_LOCK"
}

node_kernel_lock_files() {
  "$NODE_YQ_BIN" -r '[.files[] | .name + ":" + .sha256] | join(";")' "$NODE_KERNEL_SOURCE_LOCK"
}

node_kernel_package_version() {
  printf '%s%s\n' "$(node_kernel_lock_field version)" "$(node_kernel_lock_field buildSuffix)"
}

# Build ids are Kubernetes label values: no epoch, and + or ~ become -.
node_kernel_build_id_for_version() {
  local id="${1#*:}"
  id="${id//+/-}"
  id="${id//\~/-}"
  printf '%s\n' "$id"
}

node_kernel_build_id_valid() {
  local id_re='^[A-Za-z0-9]([A-Za-z0-9._-]{0,61}[A-Za-z0-9])?$'
  [[ "$1" =~ $id_re ]]
}

node_kernel_current_build_id() {
  node_kernel_build_id_for_version "$(node_kernel_package_version)"
}

node_kernel_build_dir() {
  printf '%s/%s\n' "${NODE_KERNEL_OUTPUT_ROOT%/}" "$1"
}

node_kernel_package_names() {
  local release="$1"
  printf '%s\n' \
    "linux-image-${release}" \
    "linux-base-${release}" \
    "linux-image-${NODE_KERNEL_FLAVOUR}" \
    "linux-base-${NODE_KERNEL_FLAVOUR}"
}

node_kernel_require_inputs() {
  local field value
  local name sha
  local version_re='^[0-9]+:[0-9][A-Za-z0-9.+~-]*$'
  local suffix_re='^\+btf[1-9][0-9]*$'
  local release_re="^[0-9][A-Za-z0-9.+_-]*-${NODE_KERNEL_FLAVOUR}\$"
  local name_re='^[A-Za-z0-9][A-Za-z0-9.+~_-]*$'
  local sha_re='^[0-9a-f]{64}$'
  local directory_re='^pool/[A-Za-z0-9/._+-]+$'
  local url_re='^(https?|file)://[^[:space:];]+$'

  [[ -f "$NODE_KERNEL_SOURCE_LOCK" ]] ||
    node_die "kernel source lock not found: ${NODE_KERNEL_SOURCE_LOCK}; run: just node-kernel-source-lock"
  [[ -f "$NODE_KERNEL_CONFIG_DELTA" ]] || node_die "kernel config delta not found: ${NODE_KERNEL_CONFIG_DELTA}"
  for field in version buildSuffix configDeltaSha256 kernelRelease archiveUrl directory; do
    value="$(node_kernel_lock_field "$field")"
    [[ -n "$value" ]] || node_die "kernel source lock is missing ${field}: ${NODE_KERNEL_SOURCE_LOCK}"
  done
  [[ "$(node_kernel_lock_field version)" =~ $version_re ]] ||
    node_die "invalid kernel source version in ${NODE_KERNEL_SOURCE_LOCK}"
  [[ "$(node_kernel_lock_field buildSuffix)" =~ $suffix_re ]] ||
    node_die "invalid buildSuffix in ${NODE_KERNEL_SOURCE_LOCK}"
  [[ "$(node_kernel_lock_field kernelRelease)" =~ $release_re ]] ||
    node_die "invalid kernelRelease in ${NODE_KERNEL_SOURCE_LOCK}"
  [[ "$(node_kernel_lock_field directory)" =~ $directory_re && "$(node_kernel_lock_field directory)" != *..* ]] ||
    node_die "invalid directory in ${NODE_KERNEL_SOURCE_LOCK}"
  [[ "$(node_kernel_lock_field archiveUrl)" =~ $url_re ]] ||
    node_die "invalid archiveUrl in ${NODE_KERNEL_SOURCE_LOCK}"
  while IFS=$'\t' read -r name sha; do
    [[ "$name" =~ $name_re ]] || node_die "invalid source file name in ${NODE_KERNEL_SOURCE_LOCK}: ${name}"
    [[ "$sha" =~ $sha_re ]] || node_die "invalid sha256 for ${name} in ${NODE_KERNEL_SOURCE_LOCK}"
  done < <("$NODE_YQ_BIN" -r '.files[] | [.name, .sha256] | @tsv' "$NODE_KERNEL_SOURCE_LOCK")
  [[ "$("$NODE_YQ_BIN" -r '[.files[] | select(.name | test("\\.dsc$"))] | length' "$NODE_KERNEL_SOURCE_LOCK")" == 1 ]] ||
    node_die "kernel source lock must pin exactly one .dsc: ${NODE_KERNEL_SOURCE_LOCK}"
  [[ "$(node_kernel_lock_field configDeltaSha256)" == "$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")" ]] ||
    node_die "${NODE_KERNEL_CONFIG_DELTA} does not match configDeltaSha256 in ${NODE_KERNEL_SOURCE_LOCK}; run: just node-kernel-source-lock --build-suffix <new suffix>"
  node_kernel_build_id_valid "$(node_kernel_current_build_id)" ||
    node_die "kernel build id is not a valid label value: $(node_kernel_current_build_id)"
}

node_kernel_guard_build_reuse() {
  local state_file="$1"
  local build_id="$2"
  local recorded

  [[ -f "$state_file" ]] || return 0
  recorded="$("$NODE_JQ_BIN" -r '.configDeltaSha256 // ""' "$state_file" 2>/dev/null)" || recorded=""
  [[ -n "$recorded" ]] ||
    node_die "kernel build state ${state_file} is unreadable or records no configDeltaSha256; remove it only if no node runs ${build_id}, then rerun"
  [[ "$recorded" == "$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")" ]] ||
    node_die "kernel build ${build_id} already exists with a different config delta; bump buildSuffix in ${NODE_KERNEL_SOURCE_LOCK} so nodes see a new package version"
}

node_kernel_write_build_state() {
  local build_id="$1"
  local build_dir="$2"
  local release version deb_version pkg file packages_json state_file config_file sha lock_sha delta_sha
  local sha_re='^[0-9a-f]{64}$'

  release="$(node_kernel_lock_field kernelRelease)"
  version="$(node_kernel_package_version)"
  deb_version="${version#*:}"
  packages_json='[]'
  while IFS= read -r pkg; do
    file="${build_dir}/packages/${pkg}_${deb_version}_arm64.deb"
    [[ -f "$file" ]] || node_die "kernel build did not produce ${file}"
    sha="$(node_reimage_sha256_file "$file")"
    [[ "$sha" =~ $sha_re ]] || node_die "could not hash kernel package ${file}"
    # shellcheck disable=SC2016
    packages_json="$(
      "$NODE_JQ_BIN" -c \
        --arg name "$pkg" \
        --arg file "$file" \
        --arg sha256 "$sha" \
        '. + [{name: $name, file: $file, sha256: $sha256}]' <<<"$packages_json"
    )" || node_die "could not record kernel package ${file}"
  done < <(node_kernel_package_names "$release")
  config_file="${build_dir}/packages/config-${release}"
  [[ -f "$config_file" ]] || node_die "kernel build did not produce ${config_file}"

  lock_sha="$(node_reimage_sha256_file "$NODE_KERNEL_SOURCE_LOCK")"
  delta_sha="$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")"
  [[ "$lock_sha" =~ $sha_re && "$delta_sha" =~ $sha_re ]] || node_die "could not hash the kernel build inputs"
  state_file="${build_dir}/state/kernel-build.json"
  # shellcheck disable=SC2016
  "$NODE_JQ_BIN" -n \
    --arg schema "$NODE_KERNEL_BUILD_SCHEMA" \
    --arg builtAt "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
    --arg buildId "$build_id" \
    --arg sourceVersion "$(node_kernel_lock_field version)" \
    --arg packageVersion "$version" \
    --arg kernelRelease "$release" \
    --arg lockSha256 "$lock_sha" \
    --arg configDeltaSha256 "$delta_sha" \
    --arg kernelConfig "$config_file" \
    --argjson packages "$packages_json" \
    '{
      schemaVersion: $schema,
      builtAt: $builtAt,
      buildId: $buildId,
      sourceVersion: $sourceVersion,
      packageVersion: $packageVersion,
      kernelRelease: $kernelRelease,
      lockSha256: $lockSha256,
      configDeltaSha256: $configDeltaSha256,
      kernelConfig: $kernelConfig,
      packages: $packages
    }' >"${state_file}.tmp" || {
    rm -f "${state_file}.tmp"
    node_die "could not write kernel build state ${state_file}"
  }
  mv "${state_file}.tmp" "$state_file" || node_die "could not write kernel build state ${state_file}"
  printf '%s\n' "$state_file"
}

node_kernel_verify_build_state() {
  local state="$1"
  local schema release expected_names recorded_names file sha
  local sha_re='^[0-9a-f]{64}$'

  [[ -f "$state" ]] || node_die "kernel build state not found: ${state}"
  schema="$("$NODE_JQ_BIN" -r '.schemaVersion // ""' "$state")"
  [[ "$schema" == "$NODE_KERNEL_BUILD_SCHEMA" ]] || node_die "unsupported kernel build state schema in ${state}: ${schema}"
  release="$("$NODE_JQ_BIN" -r '.kernelRelease // ""' "$state")"
  expected_names="$(node_kernel_package_names "$release" | paste -sd, -)"
  recorded_names="$("$NODE_JQ_BIN" -r '.packages | map(.name) | join(",")' "$state")"
  [[ "$recorded_names" == "$expected_names" ]] ||
    node_die "kernel build state ${state} records ${recorded_names}, expected ${expected_names}"
  while IFS=$'\t' read -r file sha; do
    [[ "$sha" =~ $sha_re ]] || node_die "kernel build state ${state} records an invalid sha256 for ${file}"
    [[ -f "$file" ]] || node_die "kernel package missing: ${file}"
    [[ "$(node_reimage_sha256_file "$file")" == "$sha" ]] || node_die "kernel package changed since build: ${file}"
  done < <("$NODE_JQ_BIN" -r '.packages[] | [.file, .sha256] | @tsv' "$state")
}

# node_kernel_require_current_build prints the state file of the kernel build
# that matches the committed source lock and config delta.
node_kernel_require_current_build() {
  local build_id state

  node_kernel_require_inputs
  build_id="$(node_kernel_current_build_id)"
  state="$(node_kernel_build_dir "$build_id")/state/kernel-build.json"
  [[ -f "$state" ]] || node_die "no kernel build for ${build_id}; run: just node-kernel-build"
  [[ "$("$NODE_JQ_BIN" -r '.lockSha256 // ""' "$state")" == "$(node_reimage_sha256_file "$NODE_KERNEL_SOURCE_LOCK")" ]] ||
    node_die "kernel build ${build_id} was built from a different source lock; run: just node-kernel-build"
  [[ "$("$NODE_JQ_BIN" -r '.configDeltaSha256 // ""' "$state")" == "$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")" ]] ||
    node_die "kernel build ${build_id} was built from a different config delta; bump buildSuffix and run: just node-kernel-build"
  node_kernel_verify_build_state "$state"
  printf '%s\n' "$state"
}
