#!/usr/bin/env bash
# shellcheck shell=bash

# Kernel source lock and build helpers for the home-ops BTF kernel. The lock
# (kernel/source.yaml) pins the Raspberry Pi OS kernel source package; builds
# live under NODE_KERNEL_OUTPUT_ROOT/<build-id>.

node_kernel_fetch() {
  local url="$1"
  local dest="$2"
  "$NODE_CURL_BIN" -fsSL --retry 3 --connect-timeout 30 -o "$dest" "$url" || node_die "download failed: ${url}"
}

# node_kernel_release_sha256_entry RELEASE PATH prints "<sha256> <size>" for PATH
# from the SHA256 section of a verified Release file.
node_kernel_release_sha256_entry() {
  local release="$1"
  local path="$2"
  awk -v path="$path" '
    /^[^ ]/ {in_sha256 = ($0 == "SHA256:")}
    in_sha256 && NF == 3 && $3 == path {print $1, $2; found = 1; exit}
    END {exit found ? 0 : 1}
  ' "$release"
}

# node_kernel_source_stanzas SOURCES PACKAGE prints every Sources paragraph whose
# Package field is exactly PACKAGE.
node_kernel_source_stanzas() {
  local sources="$1"
  local package="$2"
  awk -v package="$package" '
    BEGIN {RS = ""; FS = "\n"}
    {
      for (i = 1; i <= NF; i++) {
        if ($i == "Package: " package) {
          printf "%s\n\n", $0
          next
        }
      }
    }
  ' "$sources"
}

# node_kernel_stanza_checksums prints "<name> <sha256> <size>" per
# Checksums-Sha256 entry of the stanza on stdin.
node_kernel_stanza_checksums() {
  awk '
    /^[^ ]/ {in_block = ($0 ~ /^Checksums-Sha256:[[:space:]]*$/); next}
    in_block && NF == 3 {print $3, $1, $2}
  '
}

node_kernel_release_for_version() {
  local upstream="${1#*:}"
  printf '%s%s-%s\n' "${upstream%%-*}" "$NODE_KERNEL_ABI_SUFFIX" "$NODE_KERNEL_FLAVOUR"
}

node_kernel_write_source_lock() {
  local output="$1"
  local version="$2"
  local suffix="$3"
  local release="$4"
  local archive_url="$5"
  local directory="$6"
  local files="$7"
  local delta_sha="$8"
  local files_json

  files_json="$(
    awk 'NF == 3 {printf "%s\t%s\t%s\n", $1, $2, $3}' <<<"$files" |
      "$NODE_JQ_BIN" -R -s -c 'split("\n") | map(select(length > 0) | split("\t") | {name: .[0], size: (.[2] | tonumber), sha256: .[1]})'
  )" || node_die "could not encode kernel source files"
  mkdir -p "$(dirname "$output")"
  if ! {
    printf '%s\n' '---' \
      '# Generated by just node-kernel-source-lock. Pins the Raspberry Pi OS kernel' \
      '# source package that just node-kernel-build rebuilds with config.2712.delta.' \
      '# Hashes come from the archive Sources index after verifying the InRelease' \
      '# signature. Do not edit by hand: after changing config.2712.delta, rerun' \
      '# just node-kernel-source-lock --build-suffix with a new suffix.'
    # shellcheck disable=SC2016
    "$NODE_JQ_BIN" -n \
      --arg version "$version" \
      --arg suffix "$suffix" \
      --arg configDeltaSha256 "$delta_sha" \
      --arg release "$release" \
      --arg archive "$archive_url" \
      --arg suite "$NODE_KERNEL_ARCHIVE_SUITE" \
      --arg component "$NODE_KERNEL_ARCHIVE_COMPONENT" \
      --arg directory "$directory" \
      --argjson files "$files_json" \
      '{
        package: "linux",
        version: $version,
        buildSuffix: $suffix,
        configDeltaSha256: $configDeltaSha256,
        kernelRelease: $release,
        archiveUrl: $archive,
        suite: $suite,
        component: $component,
        directory: $directory,
        files: $files
      }' |
      "$NODE_YQ_BIN" -P
  } >"${output}.tmp"; then
    rm -f "${output}.tmp"
    node_die "could not render kernel source lock ${output}"
  fi
  mv "${output}.tmp" "$output"
}

node_kernel_lock_source() {
  local keyring="$1"
  local work_dir="$2"
  local output="$3"
  local requested_suffix="$4"
  local base="${NODE_KERNEL_ARCHIVE_URL%/}"
  local suite="$NODE_KERNEL_ARCHIVE_SUITE"
  local sources_path="${NODE_KERNEL_ARCHIVE_COMPONENT}/source/Sources.gz"
  local entry expected_sha expected_size stanzas stanza_count version directory files suffix release
  local name sha size dsc_count=0 delta_sha locked_version="" locked_suffix="" locked_delta_sha=""
  local version_re='^[0-9]+:[0-9][A-Za-z0-9.+~-]*$'
  local directory_re='^pool/[A-Za-z0-9/._+-]+$'
  local name_re='^[A-Za-z0-9][A-Za-z0-9.+~_-]*$'
  local sha_re='^[0-9a-f]{64}$'
  local size_re='^[0-9]+$'
  local suffix_re='^\+[a-z][a-z0-9]*$'

  keyring="$(cd "$(dirname "$keyring")" && pwd)/$(basename "$keyring")"
  node_log "verifying ${base}/dists/${suite}/InRelease"
  node_kernel_fetch "${base}/dists/${suite}/InRelease" "${work_dir}/InRelease"
  if ! "$NODE_GPGV_BIN" --keyring "$keyring" --output - "${work_dir}/InRelease" >"${work_dir}/Release" 2>"${work_dir}/gpgv.log"; then
    cat "${work_dir}/gpgv.log" >&2
    node_die "InRelease signature verification failed for ${base}/dists/${suite}"
  fi
  awk -v suite="$suite" '/^[^ ]/ && ($0 == "Codename: " suite || $0 == "Suite: " suite) {found = 1} END {exit found ? 0 : 1}' "${work_dir}/Release" ||
    node_die "signed InRelease is not for suite ${suite}"

  entry="$(node_kernel_release_sha256_entry "${work_dir}/Release" "$sources_path")" ||
    node_die "signed InRelease does not list ${sources_path}"
  read -r expected_sha expected_size <<<"$entry"
  node_kernel_fetch "${base}/dists/${suite}/${sources_path}" "${work_dir}/Sources.gz"
  if [[ "$(node_reimage_sha256_file "${work_dir}/Sources.gz")" != "$expected_sha" ||
    "$(wc -c <"${work_dir}/Sources.gz" | tr -d ' ')" != "$expected_size" ]]; then
    node_die "${sources_path} does not match the signed InRelease (retry if the archive was just updated)"
  fi
  gzip -dc "${work_dir}/Sources.gz" >"${work_dir}/Sources" || node_die "could not decompress ${sources_path}"

  stanzas="$(node_kernel_source_stanzas "${work_dir}/Sources" linux)"
  stanza_count="$(grep -c '^Package: linux$' <<<"$stanzas" || true)"
  [[ "$stanza_count" == 1 ]] ||
    node_die "expected exactly one linux source package in ${sources_path}, found ${stanza_count}"

  version="$(sed -n 's/^Version: //p' <<<"$stanzas")"
  directory="$(sed -n 's/^Directory: //p' <<<"$stanzas")"
  files="$(node_kernel_stanza_checksums <<<"$stanzas")"
  [[ "$version" =~ $version_re ]] || node_die "unexpected linux source version: ${version}"
  [[ "$directory" =~ $directory_re && "$directory" != *..* ]] || node_die "unexpected linux source directory: ${directory}"
  [[ -n "$files" ]] || node_die "linux source package lists no Checksums-Sha256 files"
  while read -r name sha size; do
    [[ "$name" =~ $name_re ]] || node_die "unsafe linux source file name: ${name}"
    [[ "$sha" =~ $sha_re ]] || node_die "invalid sha256 for ${name}"
    [[ "$size" =~ $size_re ]] || node_die "invalid size for ${name}"
    if [[ "$name" == *.dsc ]]; then
      dsc_count=$((dsc_count + 1))
    fi
  done <<<"$files"
  [[ "$dsc_count" == 1 ]] || node_die "linux source package must list exactly one .dsc, found ${dsc_count}"

  [[ -f "$NODE_KERNEL_CONFIG_DELTA" ]] || node_die "kernel config delta not found: ${NODE_KERNEL_CONFIG_DELTA}"
  delta_sha="$(node_reimage_sha256_file "$NODE_KERNEL_CONFIG_DELTA")"
  if [[ -f "$output" ]]; then
    locked_version="$("$NODE_YQ_BIN" -r '.version // ""' "$output")"
    locked_suffix="$("$NODE_YQ_BIN" -r '.buildSuffix // ""' "$output")"
    locked_delta_sha="$("$NODE_YQ_BIN" -r '.configDeltaSha256 // ""' "$output")"
  fi
  if [[ -n "$requested_suffix" ]]; then
    suffix="$requested_suffix"
  elif [[ "$locked_version" == "$version" ]]; then
    suffix="$locked_suffix"
  else
    suffix="+btf1"
  fi
  [[ "$suffix" =~ $suffix_re ]] || node_die "invalid kernel build suffix: ${suffix}"
  if [[ "$locked_version" == "$version" && "$locked_suffix" == "$suffix" && "$locked_delta_sha" != "$delta_sha" ]]; then
    node_die "config.2712.delta changed since ${output} pinned ${version}${suffix}; rerun with --build-suffix and a new suffix"
  fi

  release="$(node_kernel_release_for_version "$version")"
  node_kernel_write_source_lock "$output" "$version" "$suffix" "$release" "$base" "$directory" "$files" "$delta_sha"
  printf 'kernel_source_version=%s\n' "$version"
  printf 'kernel_build_suffix=%s\n' "$suffix"
  printf 'kernel_release=%s\n' "$release"
  printf 'source_lock=%s\n' "$output"
}
