---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc-local
  namespace: unifi
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
