---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsdist
  namespace: powerdns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dnsdist
  template:
    metadata:
      labels:
        app: dnsdist
    spec:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 953
        runAsGroup: 953
        fsGroup: 953
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: dnsdist
      containers:
        - name: dnsdist
          image: powerdns/dnsdist-20:2.0.3@sha256:b00c793986d98b41cf08cf4584089237d33fde4a920a211503ab8a53e8746a97
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 5m
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /etc/dnsdist/dnsdist.conf
              subPath: dnsdist.conf
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: dnsdist-config
        - name: tmp
          emptyDir: {}
