---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poweradmin
  namespace: powerdns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poweradmin
  template:
    metadata:
      labels:
        app: poweradmin
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 82
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: poweradmin
          image: ghcr.io/poweradmin/poweradmin:4.2.2@sha256:e9d75733d6eef36412fc5c02a937852275eef9a0272a749eb9378220466bab9a
          env:
            - name: DB_TYPE
              value: pgsql
            - name: DB_HOST
              value: powerdns-db-pooler-rw
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: powerdns
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: powerdns-db-app-user
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: powerdns-db-app-user
                  key: password
            - name: DNS_NS1
              value: ns1.sholdee.net
            - name: DNS_NS2
              value: ns2.sholdee.net
            - name: DNS_HOSTMASTER
              value: hostmaster@sholdee.net
            - name: PA_CREATE_ADMIN
              value: "1"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 5m
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: caddy
              mountPath: /var/caddy
            - name: db
              mountPath: /db
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          emptyDir: {}
        - name: caddy
          emptyDir: {}
        - name: db
          emptyDir: {}
        - name: tmp
          emptyDir: {}
