---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-db-app-user
  namespace: powerdns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns-db-app-user
    template:
      engineVersion: v2
      data:
        username: "{{ .PDNS_DB_APP_USER }}"
        password: "{{ .PDNS_DB_APP_PASSWORD }}"
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: powerdns-db
        decodingStrategy: Base64
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-db-superuser
  namespace: powerdns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns-db-superuser
    template:
      engineVersion: v2
      data:
        username: "{{ .DB_SUPER_USER }}"
        password: "{{ .DB_SUPER_PASSWORD }}"
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: powerdns-db
        decodingStrategy: Base64
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-db-backup-creds
  namespace: powerdns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns-db-backup-creds
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .BACKUP_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .BACKUP_KEY_SECRET }}"
  dataFrom:
    - extract:
        key: powerdns-db
        decodingStrategy: Base64
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns
  namespace: powerdns
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: powerdns
