---
# yaml-language-server: $schema=https://kube-schemas.shold.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gateway
  target:
    name: argocd-server-tls
    template:
      engineVersion: v2
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: external-wildcard
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: external-wildcard
        property: tls.key
---
# yaml-language-server: $schema=https://kube-schemas.shold.io/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: argocd-dragonfly-password
  namespace: argocd
spec:
  length: 48
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
# yaml-language-server: $schema=https://kube-schemas.shold.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dragonfly-auth
  namespace: argocd
spec:
  refreshPolicy: CreatedOnce
  target:
    name: argocd-dragonfly-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        redis-password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: argocd-dragonfly-password
