---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/0.11.1/config.schema.json
defaults:
  hidden: true
  cacheSeconds: 300
  timeseries:
    enabled: false
    maxDuration: "1h"
metrics:
  - name: kubernetes_version
    query: max by(git_version) (kubernetes_build_info{job="k3s-server"})
    value: 'labels[?"git_version"].orValue("unknown")'
    cacheSeconds: 3600
  - name: cluster_node_count
    query: count(kube_node_info)
    value: "humanizeNumber(result)"
    color: '"green"'
  - name: cluster_pod_count
    query: sum(kube_pod_info)
    value: "humanizeNumber(result)"
    color: '"green"'
    cacheSeconds: 30
  - name: cluster_cpu_usage
    query: round(avg(100 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) * 100), 0.01)
    value: 'humanizeFloat(result) + "%"'
    color: 'result <= 35.0 ? "green" : result <= 75.0 ? "orange" : "red"'
    cacheSeconds: 30
  - name: cluster_memory_usage
    query: round((sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100, 0.1)
    value: 'humanizeFloat(result) + "%"'
    color: 'result <= 75.0 ? "green" : result <= 85.0 ? "orange" : "red"'
    cacheSeconds: 30
  - name: cluster_age_days
    query: round((time() - max(kube_namespace_created{namespace="kube-system"})) / 86400)
    value: 'humanizeFloat(result) + "d"'
    color: '"green"'
    cacheSeconds: 3600
  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    value: 'humanizeFloat(result) + "d"'
    color: 'result <= 180.0 ? "green" : result <= 360.0 ? "orange" : "red"'
    cacheSeconds: 3600
