---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: kubernetes-schemas
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-credentials
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: kubernetes-schemas
        property: CLOUDFLARE_API_TOKEN
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: kubernetes-schemas
        property: CLOUDFLARE_ACCOUNT_ID
