---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crd-schema-publisher-leader-election
  namespace: kubernetes-schemas
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
