---
# yaml-language-server: $schema=https://kube-schemas.shold.io/kustomize.config.k8s.io/component_v1alpha1.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - externalsecret.yaml
  - replicationdestination.yaml
  - replicationsource.yaml
