---
# yaml-language-server: $schema=https://kube-schemas.shold.io/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  restic:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsUser: 65534
    pruneIntervalDays: 7
    repository: app-volsync-b2
    retain:
      daily: 14
      hourly: 24
    storageClassName: local-path
    unlock: u2
  sourcePVC: app-pvc
  trigger:
    schedule: "0 6 * * *"
