---
# yaml-language-server: $schema=https://kube-schemas.shold.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: crd-schema-publisher
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-credentials
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: crd-schema-publisher
        property: CLOUDFLARE_API_TOKEN
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: crd-schema-publisher
        property: CLOUDFLARE_ACCOUNT_ID
