---
# yaml-language-server: $schema=https://kube-schemas.shold.io/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crd-schema-publisher
  namespace: crd-schema-publisher
  labels:
    app: crd-schema-publisher
spec:
  selector:
    matchLabels:
      app: crd-schema-publisher
  podMetricsEndpoints:
    - port: health
      path: /metrics
