---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crd-schema-publisher-leader-election
  namespace: crd-schema-publisher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crd-schema-publisher-leader-election
subjects:
  - kind: ServiceAccount
    name: crd-schema-publisher
    namespace: crd-schema-publisher
