---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-schemas
components:
  - ../../components/namespace
resources:
  - manifests/namespace.yaml
  - manifests/serviceaccount.yaml
  - manifests/clusterrole.yaml
  - manifests/clusterrolebinding.yaml
  - manifests/role.yaml
  - manifests/rolebinding.yaml
  - manifests/externalsecret.yaml
  - manifests/deployment.yaml
