---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: powerdns
