---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/tags/external-dns-helm-chart-1.21.1/charts/external-dns/values.schema.json
policy: sync
sources:
  - gateway-httproute
  - gateway-tlsroute
  - ingress
  - crd
serviceMonitor:
  enabled: true
provider:
  name: pdns
env:
  - name: EXTERNAL_DNS_PDNS_SERVER
    value: http://powerdns-api.powerdns:8081
  - name: EXTERNAL_DNS_PDNS_API_KEY
    valueFrom:
      secretKeyRef:
        name: powerdns
        key: API_KEY
