#!/usr/bin/env bash
# shellcheck shell=bash

BOOTSTRAP_LIMA_CLUSTER_NAME_DEFAULT="${BOOTSTRAP_LIMA_CLUSTER_NAME_DEFAULT:-home-ops-k3s-test}"
BOOTSTRAP_K3S_CONFIG_DIR="${BOOTSTRAP_K3S_CONFIG_DIR:-/etc/rancher/k3s}"
BOOTSTRAP_K3S_SERVER_DIR="${BOOTSTRAP_K3S_SERVER_DIR:-/var/lib/rancher/k3s/server}"
BOOTSTRAP_K3S_TOKEN_PATH="${BOOTSTRAP_K3S_TOKEN_PATH:-${BOOTSTRAP_K3S_SERVER_DIR}/token}"
