---
# yaml-language-server: $schema=https://kube-schemas.shold.io/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: grafana
spec:
  version: docker.io/grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
  persistentVolumeClaim:
    spec:
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  config:
    analytics:
      check_for_plugin_updates: "false"
      check_for_updates: "false"
      reporting_enabled: "false"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    server:
      domain: grafana.mgmt.sholdee.net
      enable_gzip: "true"
      root_url: https://grafana.mgmt.sholdee.net
  disableDefaultAdminSecret: true
  deployment:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-secret
                      key: GF_SECURITY_ADMIN_USER
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: grafana-tmp
                  mountPath: /tmp
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
            - name: grafana-tmp
              emptyDir: {}
