---
# yaml-language-server: $schema=https://kube-schemas.shold.io/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: raspios-trixie
  namespace: system-upgrade
  labels:
    os-upgrade: raspios-trixie
spec:
  concurrency: 1
  exclusive: true
  jobActiveDeadlineSecs: 7200
  postCompleteDelay: "5m"
  version: trixie-2026-06-07
  nodeSelector:
    matchExpressions:
      - key: plan.upgrade.cattle.io/raspios-trixie
        operator: Exists
      - key: plan.upgrade.cattle.io/raspios-trixie
        operator: NotIn
        values:
          - "disabled"
          - "false"
  serviceAccountName: system-upgrade
  secrets:
    - name: raspios-upgrade-script
      path: /host/run/system-upgrade/secrets/raspios-trixie
      ignoreUpdates: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoExecute
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoSchedule
  drain:
    force: true
    skipWaitForDeleteTimeout: 180
  upgrade:
    image: debian:trixie-slim@sha256:f3da28155e2e26086464eba22cd235b22200b7143e8f3e1811bf359e3114bf96
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/raspios-trixie/upgrade.sh"]
