# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-app-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: renovate
        property: PRIVATE_KEY
        decodingStrategy: Base64
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "1070790"
  installID: "57693311"
  auth:
    privateKey:
      secretRef:
        name: github-app-pem
        key: private_key_pem
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
        RENOVATE_HOST_RULES: '[{"matchHost":"docker.io","hostType":"docker","username":"{{ .DOCKER_USERNAME }}","password":"{{ .DOCKER_PASSWORD }}"}]'
  data:
    - secretKey: DOCKER_USERNAME
      remoteRef:
        key: renovate
        property: DOCKER_USERNAME
        decodingStrategy: Base64
    - secretKey: DOCKER_PASSWORD
      remoteRef:
        key: renovate
        property: DOCKER_PASSWORD
        decodingStrategy: Base64
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-webhook-token
    template:
      engineVersion: v2
      data:
        token: "{{ .WEBHOOK_TOKEN }}"
  data:
    - secretKey: WEBHOOK_TOKEN
      remoteRef:
        key: renovate
        property: WEBHOOK_TOKEN
        decodingStrategy: Base64
