---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate
spec:
  discoveryFilter: "/sholdee/(docker-compose|caddy-proxy-cloudflare|adguard-exporter|home-ops)/"
  extraEnv:
    - name: LOG_LEVEL
      value: info
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: NODE_OPTIONS
      value: "--max-old-space-size=1024"
    - name: RENOVATE_REDIS_URL
      value: "redis://renovate-redis.renovate.svc.cluster.local:6379"
    - name: RENOVATE_REPOSITORY_CACHE
      value: enabled
    - name: RENOVATE_REPOSITORY_CACHE_TYPE
      value: "s3://renovate-cache"
    - name: AWS_REGION
      value: garage
    - name: AWS_ENDPOINT_URL
      value: "http://10.2.0.110:3900"
    - name: S3_FORCE_PATH_STYLE
      value: "true"
  provider:
    name: github
  image: renovate/renovate:43.101.2@sha256:89a1fd5861ee1c95be19f7d18669c7dcc94c516f8399436f1465e3ef3af7f452
  parallelism: 3
  schedule: "0 * * * *"
  secretRef: renovate-secret
  resources:
    requests:
      cpu: 500m
      memory: 1280Mi
    limits:
      cpu: 500m
      memory: 1280Mi
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token
