---
# yaml-language-server: $schema=https://kube-schemas.shold.io/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: powerdns
components:
  - ../../components/namespace
resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/configmap-dnsdist.yaml
  - manifests/externalsecret.yaml
  - manifests/cnpg-cluster.yaml
  - manifests/cnpg-objectstore.yaml
  - manifests/cnpg-rbac.yaml
  - manifests/deployment.yaml
  - manifests/deployment-admin.yaml
  - manifests/deployment-dnsdist.yaml
  - manifests/service.yaml
  - manifests/httproute.yaml
  - manifests/netpol.yaml
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: powerdns-db
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb
      - op: add
        path: /spec/bootstrap/recovery
        value:
          source: barman-cloud
          database: powerdns
          owner: powerdns
          secret:
            name: powerdns-db-app-user
