---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install kubeconform and actionlint
        run: |
          curl -sSLo kubeconform.tar.gz \
            "https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz"
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform
          rm kubeconform.tar.gz

          curl -sSLo actionlint.tar.gz \
            "https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz"
          tar -xzf actionlint.tar.gz actionlint
          sudo mv actionlint /usr/local/bin/actionlint
          rm actionlint.tar.gz

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
