---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validation

on:
  workflow_call:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install mise toolchain
        uses: ./.github/actions/setup-mise
        with:
          profile: validation

      - name: Run validation
        run: lefthook run pre-commit --all-files --no-auto-install
