apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.15.1@sha256:62897c85f7db1882e4c9a67e7b9eed8c227096700e02450ba61d0b99a03cc605
          env:
            - name: TZ
              value: America/Chicago
            - name: ALLOW_SIGNUP
              value: "false"
            - name: BASE_URL
              value: https://mealie.mgmt.sholdee.net
            - name: LOG_LEVEL
              value: "debug"
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_USER
              value: mealie
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-app-user
                  key: password
            - name: POSTGRES_SERVER
              value: hass-db-pooler-rw.hass.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: mealie
          envFrom:
            - secretRef:
                name: mealie
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /api/app/about
              port: http
          livenessProbe:
            httpGet:
              path: /api/app/about
              port: http
          resources:
            requests:
              memory: 500Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
