---
# yaml-language-server: $schema=https://kube-schemas.shold.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-app-user
  namespace: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-app-user
    template:
      engineVersion: v2
      data:
        username: "{{ .MEALIE_APP_USER }}"
        password: "{{ .MEALIE_APP_PASSWORD }}"
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: hass-db
        decodingStrategy: Base64
---
# yaml-language-server: $schema=https://kube-schemas.shold.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
  namespace: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie
    template:
      engineVersion: v2
      data:
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "587"
        SMTP_FROM_NAME: Mealie
        SMTP_AUTH_STRATEGY: TLS
        SMTP_FROM_EMAIL: "{{ .SMTP_USER }}"
        SMTP_USER: "{{ .SMTP_USER }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
      type: Opaque
  dataFrom:
    - extract:
        key: mealie
