---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-app-user
  namespace: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-app-user
    template:
      engineVersion: v2
      data:
        username: "{{ .MEALIE_APP_USER }}"
        password: "{{ .MEALIE_APP_PASSWORD }}"
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: hass-db
        decodingStrategy: Base64
